### ISSUE TITLE
Critical: Full display of long comments if it first comment

### ISSUE THREAD

**Issue by SKastsiukovich** [wldyslw/benefits.bugtracker#18] opened 2019-03-04 13:08 UTC
**Steps to reproduce**
Log in
Open any place without comments
Rate the place and add long  comment like a:
;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest

**Expected result**
Long comments required put in dropdown
**Actual result**
Full displaying of long comments if it first comment
![long_rew](https://user-images.githubusercontent.com/48204730/53735378-b938c500-3e97-11e9-802a-696962f61640.png)

**Comment by Alena-Shurakova** [comment] 2019-03-05 11:06
**Note**: bug reproduces in the mobile application (OS: iOS, Android), but in the mobile version long comment displays fully not depending on the order (It doesn't matter if it's first/second or any other,).

**Comment by SKastsiukovich** [comment] 2019-03-07 08:14
Still reproduce

**Comment by wldyslw** [comment] 2019-03-07 09:26
Done, will be published in the next build

**Comment by Alena-Shurakova** [comment] 2019-03-11 09:12
In **web client** version is added "Развернуть" button which hides long comments and has to give ability to see full comment after clicking it.

**Description of a bug**:
It is impossible to see full long comment and delete this comment.

**Steps to reproduce:**
1. Open any organization page
2. Rate the organization and add long comment like a:
;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest
3. Click on "Развернуть" button

**Actual result:**
1. It is impossible to see full long comment because after clicking "Развернуть" button it doesn't been shown. 
2. It is impossible to delete long comment (there are no proper button) 

**Expected result:**
1. User has possibility to see full long comment by clicking "Развернуть" button.
2. User can delete comment by clicking proper button.


**Screenshot:**
![image](https://user-images.githubusercontent.com/48205218/54111928-1a135080-43f6-11e9-9d99-e6eff863c5ff.png)

**Comment by wldyslw** [comment] 2019-03-12 07:24
Fixed in the latest release

**Comment by Alena-Shurakova** [comment] 2019-03-13 08:47
In the **web client** both problems are fixed.
Initial problem is common for **mobile version**.

**Comment by andrewworld** [comment] 2019-03-15 10:48
Fixed in last release

**Comment by Alena-Shurakova** [comment] 2019-03-18 13:11
Fixed on Android

**Comment by SKastsiukovich** [comment] 2019-03-19 08:28
Fixed

**Closed** 2019-03-19 08:28 UTC
Labels: bug, mobile app
